name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to Surge
      
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
      with:
        node-version: 16

    - name: Build and Deploy
      run: npm install -g surge
      run: surge ./parcial1rssl.surge.sh --b387dd405071619414147c8f7ced5a7e
